#!/usr/bin/env bash -eu

# For Mac OS
if [ $(uname) = 'Darwin' ]; then
  readonly mac_gnu_path="$HOME/vimnow/mac/gnu"

  export PATH="$mac_gnu_path":"$PATH"

  shopt -s expand_aliases

  for command in "date" "stat" "find" "sed"; do
    eval "alias ${command}="$mac_gnu_path"/g${command}"
  done
fi

