#!/bin/bash -eu

readonly VERSION=0.5.1

readonly vimnow_path=${VIMNOW_PATH:-~/vimnow}
readonly save_dir="$vimnow_path"/save

readonly vimnow_lib_path=${VIMNOW_LIB_PATH:-}
if [ ! -z "$vimnow_lib_path" ]; then
  readonly lib_dir="$vimnow_lib_path"
else
  readonly lib_dir="$vimnow_path"/lib
fi

source "$lib_dir"/.setting

source "$lib_dir"/options

mkdir -p "$save_dir"

file_extension=''
is_execute_script=false
continue_mode=false
for option in "$@"; do
  [ "$option" = '--sh' ] && file_extension='.sh' && is_execute_script=true
  [ "$option" = '--continue' ] && continue_mode=true
done

readonly specify_filename=${1:-}
if "$continue_mode"; then
  readonly filepath=$(find "$(vimnow --save-path)" -type f -maxdepth 1 | xargs ls -t | grep -v -e '\.swp$' | head -n 1)
elif [ ! -z "$specify_filename" ] && [[ "$specify_filename" =~ ^[a-zA-Z0-9\.]+$ ]]; then
  readonly filepath="$save_dir"/"$1"
else
  readonly unique_randomized_name=$("$lib_dir"/names-generator | perl -pe 's/_/-/g')
  readonly filepath="$save_dir"/${unique_randomized_name}-$(date -u | perl -pe 's/^\s+|\s+$//g' | perl -pe 's/\s+/-/g')-$(date +%s)"$file_extension"
fi

touch "$filepath"
chmod 0755 "$filepath"

readonly vimnow_vim_path=${VIMNOW_VIM_PATH:-}
if [ ! -z "$vimnow_vim_path" ]; then
  eval "$vimnow_vim_path" "$filepath"
else
  vim "$filepath"
fi

if [ $(stat -c '%s' "$filepath") == 0 ]; then
  rm "$filepath"
else
  if [[ -d "$save_dir"/.git ]]; then
    cd "$save_dir"
    git add $(basename "$filepath")
    git commit -m "update"
  fi
  echo "$filepath"
fi

