#!/bin/bash -eu

readonly VERSION=0.6.1

readonly vimnow_path=${VIMNOW_PATH:-~/vimnow}
readonly save_dir="$vimnow_path"/save

readonly vimnow_lib_path=${VIMNOW_LIB_PATH:-}
if [ ! -z "$vimnow_lib_path" ]; then
  readonly lib_dir="$vimnow_lib_path"
else
  readonly lib_dir="$vimnow_path"/lib
fi

source "$lib_dir"/setting

source "$lib_dir"/options

mkdir -p "$save_dir"

file_extension=''
is_execute_script=false
for option in "$@"; do
  [ "$option" = '--sh' ] && file_extension='.sh' && is_execute_script=true
done

readonly specify_filename=${1:-}
if [ ! -z "$specify_filename" ] && [[ ! "$specify_filename" =~ ^- ]]; then
  readonly filepath="$save_dir"/"$specify_filename"
else
  readonly unique_randomized_name=$("$lib_dir"/names-generator | perl -pe 's/_/-/g')
  readonly filepath="$save_dir"/${unique_randomized_name}-$(date -u | perl -pe 's/^\s+|\s+$//g' | perl -pe 's/\s+/-/g')-$(date +%s)"$file_extension"
fi

vimnow_open(){
  local open_filepath="$1"
  touch "$open_filepath"
  chmod 0755 "$open_filepath"
  
  readonly vimnow_vim_path=${VIMNOW_VIM_PATH:-}
  if [ ! -z "$vimnow_vim_path" ]; then
    eval "$vimnow_vim_path" "$open_filepath"
  else
    vim "$open_filepath"
  fi
  
  if [ $(stat -c '%s' "$open_filepath") == 0 ]; then
    rm "$open_filepath"
  else
    if [[ -d "$save_dir"/.git ]]; then
      cd "$save_dir"
      git add $(basename "$open_filepath")
      git commit -m "update"
    fi
    echo "$open_filepath"a
  fi
}

vimnow_open "$filepath"

